version: '2'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  app:
    image: 'cr.yandex/crpa08k7e03oncbsj8tb/hvorostovsky-api:latest'
    restart: always
    build:
      context: .
    container_name: hvorostovsky-api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  next-prod:
    image: 'cr.yandex/crpa08k7e03oncbsj8tb/next-prod:frontend'
    container_name: next-prod
    restart: always
    depends_on:
      - app
    ports:
      - "3000:3000"

